Adds zh-CN translation for some sections in README
Raphiiko/OyasumiVR pull request #110
Opened 2024-06-26 01:39 UTC by inkuxuan

2024-06-26 01:46 UTC, flower-elf requested changes

2024-06-26 01:46 UTC, flower-elf commented on docs/readmes/src/cn/texts.txt
> +支援Oyasumi VR
在简体中文中一般使用“支持”而不是“支援”，在此处也可以使用“赞助”一类的词语

2024-06-26 01:46 UTC, flower-elf commented on docs/readmes/src/cn/texts.txt
> +控制头显亮度目前只支持 Valve Index 和 Bigscreen Beyond。
```suggestion
头显亮度控制功能目前只支持 Valve Index 和 Bigscreen Beyond。
```

2024-06-26 01:51 UTC, inkuxuan commented on docs/readmes/src/cn/texts.txt
> +支援Oyasumi VR
Rewording suggestion committed by 8fbcc1999125a016227f17a742c41ce037280b31

2024-06-26 01:52 UTC, inkuxuan commented on docs/readmes/src/cn/texts.txt
> +控制头显亮度目前只支持 Valve Index 和 Bigscreen Beyond。
Rewording suggestion committed by 8fbcc1999125a016227f17a742c41ce037280b31

2024-06-26 01:52 UTC, flower-elf approved these changes

2024-06-29 12:47 UTC, Raphiiko commented
Thanks for the updates!

2024-06-29 12:47 UTC, merged